### ISSUE TITLE
yarn global add doesn't create ref-resolver command

### ISSUE THREAD

**Issue by skplunkerin** [en-ken/json-yaml-ref-resolver#5]
When installing with `yarn`:

```
yarn global add json-yaml-ref-resolver
```

It should perform the same way as installing with `npm`:

```
npm i -g json-yaml-ref-resolver
```

But the `ref-resolver` CLI command isn't created when using `yarn`.

---

_BTW this is amazing! Thank you!_

**Comment by en-ken** [comment]
Thanks for your report.
I'll fix this soon.
